### ISSUE TITLE
Connect Liberapay members

### ISSUE THREAD

**Issue by MartinDelille** [liberapay/liberapay.org#16]
Hi!

Since we are part of the organization, I would found useful to connect in order to better know each other. My contact information are all listed here: http://www.martindelille.com
Feel free to add me to the network you use the most!

**Comment by Changaco** [comment]
Nice CV. :-) I thought I was already following you on Twitter, but I wasn't.

Most of my info is in my Liberapay profile: https://liberapay.com/Changaco/
