### ISSUE TITLE
Élection du représentant légal

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.org#19]
*It's time for the election of Liberapay's legal representative, as my mandate ends on December 19th (<https://github.com/liberapay/liberapay.org/issues/2#issuecomment-166003076>). This issue will be discussed in French for simplicity.*

---

C'est le moment d'élire le représentant légal de Liberapay, car mon mandat se termine le 19 décembre. Il y a 4 candidats possibles : moi, @Zatalyz, @MartinDelille, et @MarionRousseaux. La décision est au consensus. Les 4 candidats sont aussi les seules personnes ayant le droit de vote.

**Comment by Zatalyz** [comment]
Je propose de renouveler ton mandat. Je suis très satisfaite de la façon dont tu gère les choses :P Donc mon vote, à ce stade est : vive Changaco !

**Comment by Changaco** [comment]
Je suis d'accord pour continuer à être le représentant légal. @MartinDelille et @MarionRousseaux : des objections ?

**Comment by MarionRousseaux** [comment]
Bien sûr que non, aucune objection. Au plaisir de suivre l'évolution du
projet et de pouvoir contribuer si besoin.

Bonne soirée à vous !

**Comment by MartinDelille** [comment]
Avec un peu de retard: pas d'objection de ma part non plus, je vote donc pour @Changaco qui gère de façon admirable!

**Comment by Changaco** [comment]
OK, la décision est donc validée à l'unanimité. Merci pour vos réponses. :-)

---

*I have been unanimously reelected as legal representative for one more year. README update: 0b59190a70751faaabd6e2d787adc762fb966a52.*
