### ISSUE TITLE
Create and register the association

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.org#2]
Now that the bylaws are (pretty much) done, we have to actually sign them. How shall we proceed?

*Maintenant que les statuts sont finis (ou presque), il faut les signer. Comment procède-t-on ?*

**Comment by Changaco** [comment]
The bylaws need to be signed by two founding members who are administrators of the organization ([official source](https://www.service-public.fr/associations/vosdroits/F1119)). Since all Liberapay members will be codirectors, any two can sign.

There doesn't seem to be a procedure to cryptographically sign this kind of contract, so we have to do it the old-fashioned way: by hand.

**Comment by Changaco** [comment]
The bylaws have been signed by me and @Zatalyz.

The election of the representatives is done: @Zatalyz didn't want to take on this role, I was elected.

The next step is to [register the association](https://mdel.mon.service-public.fr/gestion-association.html), I'm starting that now.

**Comment by Changaco** [comment]
Done. Let's hope it doesn't get rejected.

**Comment by Changaco** [comment]
\o/ Looks like I filled out the paperwork properly. :-) The last step is publication in the *Journal Officiel*, that costs about 40€. :-(

**Comment by Changaco** [comment]
\o/ The association has been [published in the *Journal Officiel*](http://www.journal-officiel.gouv.fr/publications/assoc/pdf/2016/0002/JOAFE_PDF_Unitaire_20160002_00157.pdf).

**Comment by Azanp** [comment]
We are also provide crack software. It has a wonderful feature. This is a good job. It is easy to use. 
https://azanpc.com/microsoft-office-365-crack-free-download/
