### ISSUE TITLE
Élection du représentant légal pour 2018

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.org#27]
[fr] C'est le moment d'élire le représentant légal de Liberapay, car mon mandat se termine le 19 décembre. Il y a 4 candidats possibles : moi, @Zatalyz, @MartinDelille, et @MarionRousseaux. La décision est au consensus. Les 4 candidats sont aussi les seules personnes ayant le droit de vote. Année précédente : #19.

[en] It's time for the election of Liberapay's legal representative, as my mandate ends on December 19th. Previous election: #19.

**Comment by revi** [comment]
How long is the term of the legal representative?

**Comment by Changaco** [comment]
1 year, per https://github.com/liberapay/liberapay.org/blob/v1/en/rules_of_procedure.md#article-3-representation

**Comment by Zatalyz** [comment]
Si cela te conviens, Changaco, je souhaiterais que tu continue à nous représenter. Tu es celui qui connais le mieux Liberapay d'entre nous, et qui y consacre le plus de temps, donc je vote pour toi :)

**Comment by MartinDelille** [comment]
I vote for @Changaco

**Comment by Changaco** [comment]
[fr] Deux votes en ma faveur et aucune objection, je suis donc réélu.

[en] Two votes for me and no objections, I am reelected.

https://github.com/liberapay/liberapay.org/commit/cca883dcbfaa89b1062ed08304abe3d17d22431e
