### ISSUE TITLE
request the @liberapay handle on Twitter

### ISSUE THREAD

**Issue by maxlath** [liberapay/liberapay.org#28]
you might have the possibility to request the right to use [@liberapay on twitter](https://twitter.com/liberapay) based on [Twitter Inactive account policy](https://support.twitter.com/articles/15362), if you can show that you have a registered trademark on the name: maybe having registered a legal entity with the name is enough?
It's not that much a big deal, but it does make mentionning liberapay less error prone.
Thanks for this great project!

**Comment by Changaco** [comment]
We've already tried to get the account: the owner never answered, and Twitter doesn't give a fuck because we don't have a registered trademark.

**Comment by Changaco** [comment]
I submitted another impersonation report. They probably don't read those at all though.

I'm thinking of tweeting this next week:

> If someone from @TwitterSupport reads this: please help us out with case #74188854. Everyone else: please retweet. Thanks. 😘

**Comment by Changaco** [comment]
I sent an email to Twitter support instead, and they've agreed to transfer the username to us!

**Comment by trebmuh** [comment]
Good job with your tenacity!

**Comment by Changaco** [comment]
The rename is done and [announced](https://github.com/liberapay/salon/issues/193#issuecomment-355742191).
