### ISSUE TITLE
Adult content

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.org#29]
We've received two questions today about using Liberapay to fund adult content. Obviously there's nothing against it in our terms, so as usual it comes down to mangopay's policies. I looked through [their terms](https://liberapay.com/about/legal#mangopay-terms) again and didn't find any explicit clause against adult content. The related section "9. User Commitments" is worded in a broad general way:

> The User guarantees that no part of its profile on the Website will harm the rights of third parties or is contrary to the law, to public order or to accepted principles of morality.
>
> The User undertakes not to:
>
> - Execute the Framework Contract in an illegal manner or in conditions that are likely to
damage, deactivate, overload or impair the Website;
> - Assume the identity of another person or entity, falsify or conceal his/her identity or age, or
create any false identity; or
> - Disseminate personal data or information concerning a third party, such as postal addresses,
telephone numbers, email addresses, bank card numbers etc.
>
> In the event of User default, the Issuer reserves the right to take any appropriate measures in order to stop the relevant actions. The Issuer will also be entitled to suspend and/or block access to the Account.

**Comment by jorgesumle** [comment]
So why is this an issue?

**Comment by Changaco** [comment]
Many payment processors refuse adult content as it's considered to have a higher risk of chargebacks. I think we should be fine since we're processing donations, not sells of adult content, but I would feel better with an explicit "okay" from mangopay.

**Comment by jorgesumle** [comment]
Oh, I see. But I'm almost sure that they can't charge Liberapay more if they don't say that explicitly in their terms of services.

The problematic part for me is

> or to accepted principles of morality.

What are "accepted principles of morality"? That may vary from person and from country. Ask Mangopay if funding adult content through donations is an "accepted principle of morality" to make sure we are OK.

**Comment by Changaco** [comment]
I'm not worried about mangopay charging us more, I'm worried about them banning people.

**Comment by Changaco** [comment]
I've just sent an email to mangopay.

**Comment by Changaco** [comment]
I received a response from Mangopay containing a link to their [list of prohibited businesses](https://www.mangopay.com/prohibited-businesses/) and saying that they can't process any kind of payment related to adult content, not even anonymous donations.

**Comment by swedneck** [comment]
Since liberapay no longer uses mangopay, does this mean adult content is now allowed?

**Comment by Changaco** [comment]
No. There are very few payment processors who accept adult creators, Stripe and PayPal don't (see [Stripe's Prohibited Businesses](https://stripe.com/prohibited-businesses) and [PayPal's Acceptable Use Policy](https://www.paypal.com/us/webapps/mpp/ua/acceptableuse-full)).

**Comment by Changaco** [comment]
See also: [Alternatives To Patreon For Porn Creators](http://msnaughty.com/blog/2018/07/03/alternatives-to-patreon-for-porn-creators/).

**Comment by MartinDelille** [comment]
I play in a band: https://cocksuckers.bandcamp.com/releases

Can we get funded on Liberapay?

**Comment by mattbk** [comment]
@changaco that was more than I ever needed to learn about hosting that type of content.
