### ISSUE TITLE
Open a bank account

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.org#3]
Which bank? How about [La Banque Postale](https://www.labanquepostale.fr/)? Is there any reason not to choose that one?

What do we need? Maybe a debit card to pay for the few things the organization is supposed to pay for, like servers. On the other hand we probably don't need cheques.

**Comment by Changaco** [comment]
Found [Holvi](https://about.holvi.com/en/) by searching for "european online bank". The [pricing](https://about.holvi.com/en/holvi-pricing/) is: 0.90 euros for incoming and outgoing payments, 3% for credit card payments.

Unfortunately signing up from France only adds you to a waiting list:

> Great to have you on board!
>
> You have successfully secured a spot on our early access list. We are working hard to make Holvi available in your country. You'll be the first to know when we are ready to onboard you.
>
> Tweet us about your project and move forward on our early access list!

**Comment by Changaco** [comment]
[The world’s best bank accounts for international travelers and nomads](https://medium.com/nomad-gate/the-world-s-best-bank-accounts-for-international-travelers-and-nomads-3257e6839cff)

**Comment by Changaco** [comment]
[Conversation with Holvi](https://twitter.com/Changaco/status/681148369583104002)

**Comment by Changaco** [comment]
French banks' fees for small non-profit organizations are outrageous, many times higher than for personal accounts, for the same service.

**Comment by Changaco** [comment]
Looks like [Credit Mutuel](https://www.creditmutuel.fr/) is the best and cheapest option, possibly entirely free if we use their website only once or twice a month. [Source (page 11)](https://www.creditmutuel.fr/cmmabn/fr/info/_telechargement/pdf/reglementaire/Convention_clarte_pro_asso_agri_2016.pdf#page=11).

What do you think @Zatalyz?

**Comment by finkiki** [comment]
As a french association, do you must have a bank account in France ?

**Comment by Changaco** [comment]
@finkiki We need a bank account in the [Single Euro Payments Area](https://en.wikipedia.org/wiki/Single_Euro_Payments_Area), not necessarily France. Holvi was the best option, but they don't want to open up to France yet, and other European online banks seem to only offer accounts for individuals, or charge crazy fees for organization accounts, so we're back to square one: french banks.

**Comment by Changaco** [comment]
I have finally heard back from Crédit Mutuel, they seem to confirm that we can get account pretty much for free. I asked them if I could open an account via internet, but they said no, so I'll probably go see them next week.

**Comment by Changaco** [comment]
\o/ We have a bank account. \o/
