### ISSUE TITLE
Non-refundable fraudulent transactions

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.org#36]
We need to figure out what to do when we have money whose origin is fraudulent and we can't refund it.

**Comment by trebmuh** [comment]
What kind of scenario do you have in mind?

Principles' suggestion: donation to "Resto du cœur".

**Comment by Changaco** [comment]
When I recently tried to clean up suspicious accounts I got errors saying that card payments older than 11 months can't be refunded.

**Comment by Changaco** [comment]
I'm going to leave the suspicious funds in the Mangopay wallets.
