### ISSUE TITLE
5th member

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.org#38]
Current KYC (Know Your Customer) regulations require collecting information on any person who has 25% or more control over a business or organization. Liberapay currently has 4 codirectors, so each one of us has 25% of the voting rights. Adding a 5th member would lower that number to 20% and save me from having to fill an annoying UBO (Ultimate Beneficial Owners) form every time I create a new payment account for the org.

**Comment by Changaco** [comment]
Now that Zatalyz quit (#39) we would need at least two new members. Any candidates? ping @jelv @jorgesumle @mattbk @revi @trebmuh

Alternatively we could rewrite the bylaws and rules of procedure so that the association can have many members but only one or two administrators.

**Comment by revi** [comment]
@Changaco I am happy to help, as long as I don't need to move to France or learn French (I guess all is fine though >_>)

Also any documentation about the obligation of members?

**Comment by Changaco** [comment]
You don't need to live in France or speak French.

There aren't really any obligations for members, except that I will need some personal information from you (name, nationality, profession, postal address) in order to submit the new list of directors to the French administration. However being a co-director does make you co-responsible of the actions of the association, so theoretically you could be convicted of something if the Liberapay org was sued.

The only documentation we currently have are the bylaws and rules of procedure themselves: <https://github.com/liberapay/liberapay.org/tree/master/en>.

**Comment by jorgesumle** [comment]
I can help with that. I've just sent you all the information you need by email. I agree with the documentation.

**Comment by mattbk** [comment]
Thanks for the ping, but I'm not in a position to do this right now. Props to @jorgesumle for stepping up!

**Comment by jelv** [comment]
Thanks for the ping but this is not a possibility for me right now.

**Comment by trebmuh** [comment]
Thanks for the ping too. Unfortunately, I'm starting some new activities those weeks which take a big amount of my available time.

Reading at the thread here, with @jorgesumle and @revi , everthing is fine from you POV @Changaco , isn't?

**Comment by Changaco** [comment]
So, now that we've heard from everyone, it's time to vote.

@MartinDelille @MarionRousseaux Are you in favor of @jorgesumle and @revi becoming codirectors?

**Comment by MartinDelille** [comment]
Yes I do!

**Comment by Changaco** [comment]
Okay then, welcome @jorgesumle and @revi!

@jorgesumle @revi You can fill in https://liberapay.com/about/me/identity now, the data no longer goes to Mangopay (except for users who still have funds in a wallet).

**Comment by revi** [comment]
Data saved.

**Comment by Changaco** [comment]
Paperwork done.
