### ISSUE TITLE
Resignation / Démission

### ISSUE THREAD

**Issue by Zatalyz** [liberapay/liberapay.org#39]
[FR] :fr: 
Bonjour à toutes et tous,
Je vous annonce publiquement ma démission du Comité Directeur de Liberapay, à compter de ce jour. Mes problèmes de santé ont empirés au cours de la dernière année et je recentre mon énergie sur les projets où je peux faire avancer les choses. J'en avais parlé il y a quelques mois avec Changaco et les récents soucis avec Mangopay me confirment la nécessité de laisser ma place. Bonne continuation !

[EN] :gb: 
Hello everyone,
I am publicly announcing my resignation from the Liberapay Board of Directors, effective today. My health problems have gotten worse over the past year and I am refocusing my energy on projects where I can make a difference. I had talked about it a few months ago with Changaco and the recent problems with Mangopay confirm the need to leave my place. Keep up the good work! (Translated with www.DeepL.com/Translator)

**Comment by revi** [comment]
Hi Zatalyz, thank you for your work till now, and get well soon!

**Comment by MartinDelille** [comment]
Thank you @Zatalyz for all the work you've achieve on the project! You are totally right to focus on your health first and I wish you to recover soon!

**Comment by trebmuh** [comment]
[FR]
Tristesse.
Bonne continuation @Zatalyz !

[EN]
Sadness.
Keep it up @Zatalyz !

**Comment by jelv** [comment]
Thank you for your hard work. Good recovery and all the best in your future endeavours.
