### ISSUE TITLE
Information request from Germany

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.org#47]
Today I received a letter from a German prosecutor (*Staatsanwalt*), dated July 7th, requesting information about a Liberapay account owner. The envelope contains both the original letter in German and a French translation of it.

The prosecutor wants: the person's name, postal address, email address, and bank account details. We only have: two email addresses, and partial bank account information (through Stripe). The account owner appears to be in the United States.

**Comment by revi** [comment]
Do we provide such information to law enforcement people without requiring a valid French court warrants / order (place of incorporation)? Or is there an EU stuff that makes warrants unnecessary (because I don't live in EU and IANAL)?

**Comment by Changaco** [comment]
The last paragraph of the letter states that it was sent directly from Germany in accordance with article 5 of the EU convention on mutual assistance in criminal matters ([EUR-Lex - 02000A0712(01)-20000712 - EN](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02000A0712(01)-20000712)):

> #### Article 5 - Sending and service of procedural documents
>
> 1\.  Each Member State shall send procedural documents intended for persons who are in the territory of another Member State to them directly by post.
> 
> 2\.  Procedural documents may be sent via the competent authorities of the requested Member State only if:
> 
> (a) the address of the person for whom the document is intended is unknown or uncertain; or
> 
> (b) the relevant procedural law of the requesting Member State requires proof of service of the document on the addressee, other than proof that can be obtained by post; or
> 
> (c) it has not been possible to serve the document by post; or
> 
> (d) the requesting Member State has justified reasons for considering that dispatch by post will be ineffective or is inappropriate.
> 
> 3\.  Where there is reason to believe that the addressee does not understand the language in which the document is drawn up, the document, or at least the important passages thereof, must be translated into (one of) the language(s) of the Member State in the territory of which the addressee is staying. If the authority by which the procedural document was issued knows that the addressee understands only some other language, the document, or at least the important passages thereof, must be translated into that other language.
> 
> 4\.  All procedural documents shall be accompanied by a report stating that the addressee may obtain information from the authority by which the document was issued or from other authorities in that Member State regarding his or her rights and obligations concerning the document. Paragraph 3 shall also apply to that report.
> 
> 5\.  This Article shall not affect the application of Articles 8, 9 and 12 of the European Mutual Assistance Convention and Articles 32, 34 and 35 of the Benelux Treaty.

Is Liberapay obligated to provide the requested information? I don't know. Should we try to find out? I don't think so. I'm in favor of sending the limited amount of information we have.

**Comment by mattbk** [comment]
I am not a lawyer, but I don't think a request like this ever requires you to provide information you don't already have. That is, even if it's a simple matter to determine a person's postal address based on other information Liberapay has, it's not Liberapay's job to determine that, it's the prosecutor's job.

**Comment by revi** [comment]
I'm not really a fan of providing any information to Law Enforcement (hereinafter LE) without court order/warrants thanks to the stuff Korean LE did in the past (doing shady things in the name of 'info request' that wouldn't get court approvals) but things might be different in EU so if you want to pursue that route I'm not in a 'hell no' position.

**Comment by Changaco** [comment]
The reasons why I'm inclined to respond positively are:

- Providing the limited information we have doesn't seem problematic.
  - The two email addresses can be obtained by other means: one because it's exposed through PayPal, and the other because it's easy to guess (`admin@…`).
  - The user's apparent country of residence may discourage the prosector from pursuing the investigation. If the “target” is indeed a US citizen living in the US, then the German law referenced in the letter is probably inapplicable.
- Complying seems like the fastest way to close the issue. If we reject the request, then it's more likely that we'll receive further letters, and I don't want to waste time on this.

**Comment by jorgesumle** [comment]
To be safe I would send the information they want, unless you agree on paying a lawyer to sort this out, but I think it's not worth it. If there is an ongoing investigation in Germany, maybe Liberapay must to provide the information. Why take the risk? If they keep pushing, they will get what they want anyway.

**Comment by Changaco** [comment]
I've sent a response. There was no email address in the letter we received but there was a fax number, so I've sent the response by fax using my dad's old number.
