### ISSUE TITLE
Resignation / Démission

### ISSUE THREAD

**Issue by MartinDelille** [liberapay/liberapay.org#49]
[FR] 🇫🇷
Bonjour à toutes et tous,

N'étant plus impliqué dans le projet depuis plusieurs mois, je souhaiterai démissionner du comité de direction de Liberapay.

Je vous souhaite une bonne continuation!

[EN] 🇬🇧
Hello everyone,

Since I'm not implicated in the project since many months, I would like to resign of the Liberapay board of directors.

I wish you a good continuation!

**Comment by Changaco** [comment]
This resignation is now officially recorded.
