### ISSUE TITLE
Resignation (revi)

### ISSUE THREAD

**Issue by revi** [liberapay/liberapay.org#53]
Hi,

I got a new job, and since South Korea's anti-corruption legislation do not allow me to sit as a co-director of external organization without explicit written approval of new employer, I am resigning, effective 2021-09-01 (Sept. 1, 2021).

**Comment by Changaco** [comment]
I've started the paperwork for the official declaration of your resignation.

I hadn't declared Martin's resignation yet (#49), so it'll be done at the same time. Better late than never.

I've sent an email to @MarionRousseaux to ask her if she still wants to be codirector (and confirm her postal address if that's the case).

**Comment by Changaco** [comment]
The paperwork is done and submitted.
