### ISSUE TITLE
Exclusion of @MarionRousseaux

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.org#54]
I haven't received a response to the email I sent to Marion last week (<https://github.com/liberapay/liberapay.org/issues/53#issuecomment-912937828>), so I'm initiating a vote to officially terminate her codirectorship, in accordance with [article 4 of the rules of procedure](https://github.com/liberapay/liberapay.org/blob/master/en/rules_of_procedure.md#article-4-exclusion):

> The exclusion of a member requires the approval of an absolute majority of members. The vote lasts one week, during this time the voters can change their votes and the targeted member can defend themself or resign.

@jorgesumle You and I are the only two active codirectors left, so your vote is decisive.

**Comment by jorgesumle** [comment]
OK. if she answers and still wants to be codirector, we can add her back.

**Comment by Changaco** [comment]
The decision to exclude Marion is now officially recorded.

@jorgesumle Thanks for your quick response.
