### ISSUE TITLE
“Wise” wants to check the identities of all “significant controllers” of the Liberapay org

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.org#56]
Liberapay received the following email from [Wise](https://wise.com/) last week:

> Hello Charly,
> 
> From time to time we have to make sure that our customers’ details are up to date. Therefore we’re asking you to share some information about the individual stakeholders behind Liberapay.
> 
> **Please reply to this email with the following information:**
> 
> * Full name, date of birth and country of residence for each director or member of the executive board
> 
> **Please also securely upload the following:**
> 
> * A clear copy of a photo ID for each owner and significant controller (driving license photocard, passport photo page or national ID card): https://wise.com/document-upload/business/beneficial-owner-identity
> 
> * A document listing the members of the board of directors, managing partners or executive management (often found in an incorporation document, memorandum, board minutes, or similar): https://wise.com/document-upload/business/director-document
> 
> Should you have any questions, please don’t hesitate to ask — we’re always happy to help!
> 
> Thanks,
> The Wise Team

@jorgesumle Since you and I are the only two directors left, we can both be considered “significant controllers”. Uploading a copy of my ID card isn't a problem, but I don't know about you. Would you be able and willing to upload a copy of your ID?

**Comment by jorgesumle** [comment]
Wait, we don't have Wise integration yet, or did I miss something?

> Would you be able and willing to upload a copy of your ID?

Yes, I can do that.

**Comment by Changaco** [comment]
No, we don't have a Wise integration, and I'm not working on one.

A Wise account is basically an online multi-currency bank account. The Wise account has become the main bank account of the Liberapay org.

I'll let you know how to upload a copy of your ID once I've figured it out.

**Comment by Changaco** [comment]
@jorgesumle I've added you as an admin of the Wise account in the hope that you'll be able to upload your ID directly at <https://wise.com/document-upload/business/beneficial-owner-identity>. Let me know if it works or not.

**Comment by jorgesumle** [comment]
I uploaded the documents; it says they need 1-2 days to review the documents.

**Comment by Changaco** [comment]
“Thanks for sharing all the information we requested. We’ve now confirmed your details and your account is ready to use.”
